include: [.htaccess]
exclude: [README.md]
url:
permalink: pretty
pagination:
future: false
title:
author:
description:
language: en-GB
ms-colour:
social:
    facebook:
    google:
    twitter:
version:
    css:
    js:
jquery:
    version: